server.port: 8081

logging.level.root: INFO

spring:
  activemq:
    broker-url: tcp://192.168.75.129:61616

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.129:3306/bingo?useUnicode=true&characterEncoding=utf8
    username: root
    password: MyNewPassword0080!
    initialize: true
    max-active: 20
    validation-query: SELECT 1

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy




